### ISSUE TITLE
ChunkyPipes encountered an error when trying to execute run:

### ISSUE THREAD

**Issue by biopelayo** [tbrunetti/GWAS_QC_pipeline_ver_1.0#1]
Hi all,
I'm a biologist learning bioinformatics.
Trying to run the pipeline I have this error when running Basic Mode example:

 `**chunky run run_GWAS_QC_filtering_pipeline.py -sampleTable /home/usuario/my_project/GWAS_QC_pipeline/SampleTable.txt -snpTable /home/usuario/my_project/GWAS_QC_pipeline/SNPTable.txt -inputPLINK /home/usuario/my_project/GWAS_QC_pipeline/toy.ped**`

Does anybody could help to find the problem? It is a common one?
I followed the readme instructions step by step and everything was correct. All programs and dependencies and files are in the same folder.
Thank you in advance and congrats for the pipeline!

Pelayo

Traceback (most recent call last):
  File "/home/usuario/miniconda2/lib/python2.7/site-packages/chunkypipes/util/__init__.py", line 74, in execute_from_command_line
    chunky_command_classes[subcommand].run(argv[2:])
  File "/home/usuario/miniconda2/lib/python2.7/site-packages/chunkypipes/util/commands/run.py", line 44, in run
    pipeline_config=pipeline_class.pipeline_config
  File "/home/usuario/miniconda2/lib/python2.7/site-packages/chunkypipes/components/__init__.py", line 467, in _run_pipeline
    self.run_pipeline(pipeline_args=pipeline_args, pipeline_config=pipeline_config)
  File "run_GWAS_QC_filtering_pipeline.py", line 345, in run_pipeline
    inputPlinkfile=pipeline_args['inputPLINK'], plink=pipeline_config['plink']['path']
  File "run_GWAS_QC_filtering_pipeline.py", line 59, in check_input_format
    convert = subprocess.call([str(plink), '--file', str(inputPlinkfile[:-4]), '--make-bed', '--out', str(inputPlinkfile[:-4])])
  File "/home/usuario/miniconda2/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/usuario/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/usuario/miniconda2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by biopelayo** [comment]
@tbrunetti ???

**Comment by tbrunetti** [comment]
@biopelayo 

Sorry for the delayed response, I have been on a mini-vacation and I am just now catching up on emails.  This problem occurs because a file you have listed in your pipeline call or configuration file does not exist.  Please check the file paths.  Also, can you check your configuration paths? This can be done by running 

```
chunky configure run_GWAS_QC_filtering_pipeline.py
```
I will try to release a minor revision to the code that has better error calling so it is easier to decipher.  Let me know what you find.

**Comment by biopelayo** [comment]
Hello, Tonya.
Thank you for your response and forgive my impatience, 
as you know the biologists we are learning to program we are alone
 and frustrated most of the time.
I'm going to restart the whole process again and if I still have problems
 I'll write you here.
I thank you very much for your time.
Pelayo

**Comment by tbrunetti** [comment]
> Hello, Tonya.
> Thank you for your response and forgive my impatience,
> as you know the biologists we are learning to program we are alone
> and frustrated most of the time.
> I'm going to restart the whole process again and if I still have problems
> I'll write you here.
> I thank you very much for your time.
> Pelayo

No problem!  I understand the frustration.  My degree is actually in molecular biology before I added a computer science degree.  If you have any questions or suggestions, please let me know.  I am going to close this thread for now.
